server:
  error:
    include-message: always
  port: 5039
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentTestWithMockito?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1590
  jpa:
    hibernate:
      ddl-auto: create
